version: '3.3'

services:
  time_amarelo:
    build: .
    image: labind-ssl-ai:latest
    container_name: ssl_amarelo
    network_mode: "host"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py", "--team", "yellow"]

  time_azul:
    build: .
    image: labind-ssl-ai:latest
    container_name: ssl_azul
    network_mode: "host"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py", "--team", "blue"]