# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameSettings.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12GameSettings.proto\x12\x05proto\"\xc0\x01\n\x0cGameSettings\x12\x15\n\ris_primary_ai\x18\x01 \x01(\x08\x12\x11\n\tis_yellow\x18\x02 \x01(\x08\x12\x0f\n\x07is_left\x18\x03 \x01(\x08\x12\x38\n\x0erobot_hub_mode\x18\x04 \x01(\x0e\x32 .proto.GameSettings.RobotHubMode\";\n\x0cRobotHubMode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x42\x41SESTATION\x10\x01\x12\r\n\tSIMULATOR\x10\x02\x62\x06proto3')
)



_GAMESETTINGS_ROBOTHUBMODE = _descriptor.EnumDescriptor(
  name='RobotHubMode',
  full_name='proto.GameSettings.RobotHubMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASESTATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMULATOR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=222,
)
_sym_db.RegisterEnumDescriptor(_GAMESETTINGS_ROBOTHUBMODE)


_GAMESETTINGS = _descriptor.Descriptor(
  name='GameSettings',
  full_name='proto.GameSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_primary_ai', full_name='proto.GameSettings.is_primary_ai', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_yellow', full_name='proto.GameSettings.is_yellow', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_left', full_name='proto.GameSettings.is_left', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_hub_mode', full_name='proto.GameSettings.robot_hub_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAMESETTINGS_ROBOTHUBMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=222,
)

_GAMESETTINGS.fields_by_name['robot_hub_mode'].enum_type = _GAMESETTINGS_ROBOTHUBMODE
_GAMESETTINGS_ROBOTHUBMODE.containing_type = _GAMESETTINGS
DESCRIPTOR.message_types_by_name['GameSettings'] = _GAMESETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameSettings = _reflection.GeneratedProtocolMessageType('GameSettings', (_message.Message,), dict(
  DESCRIPTOR = _GAMESETTINGS,
  __module__ = 'GameSettings_pb2'
  # @@protoc_insertion_point(class_scope:proto.GameSettings)
  ))
_sym_db.RegisterMessage(GameSettings)


# @@protoc_insertion_point(module_scope)
