# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotFeedback.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotFeedback.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13RobotFeedback.proto\x12\x05proto\"\x9b\x02\n\rRobotFeedback\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1d\n\x15\x62\x61ll_sensor_sees_ball\x18\x02 \x01(\x08\x12\x1e\n\x16\x62\x61ll_sensor_is_working\x18\x04 \x01(\x08\x12\x1a\n\x12\x64ribbler_sees_ball\x18\x05 \x01(\x08\x12\x1c\n\x14\x65stimated_velocity_x\x18\x06 \x01(\x01\x12\x1c\n\x14\x65stimated_velocity_y\x18\x07 \x01(\x01\x12\x15\n\restimated_yaw\x18\x08 \x01(\x01\x12\x1b\n\x13xsens_is_calibrated\x18\t \x01(\x08\x12\x1c\n\x14\x63\x61pacitor_is_charged\x18\n \x01(\x08\x12\x15\n\rbattery_level\x18\r \x01(\x02\"\x8b\x01\n\x0eRobotsFeedback\x12\x1e\n\x04team\x18\x01 \x01(\x0e\x32\x10.proto.RobotTeam\x12*\n\x06source\x18\x02 \x01(\x0e\x32\x1a.proto.RobotFeedbackSource\x12-\n\x0frobots_feedback\x18\x03 \x03(\x0b\x32\x14.proto.RobotFeedback*+\n\tRobotTeam\x12\x0f\n\x0bYELLOW_TEAM\x10\x00\x12\r\n\tBLUE_TEAM\x10\x01*5\n\x13RobotFeedbackSource\x12\r\n\tSIMULATOR\x10\x00\x12\x0f\n\x0b\x42\x41SESTATION\x10\x01\x62\x06proto3')
)

_ROBOTTEAM = _descriptor.EnumDescriptor(
  name='RobotTeam',
  full_name='proto.RobotTeam',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='YELLOW_TEAM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE_TEAM', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=458,
  serialized_end=501,
)
_sym_db.RegisterEnumDescriptor(_ROBOTTEAM)

RobotTeam = enum_type_wrapper.EnumTypeWrapper(_ROBOTTEAM)
_ROBOTFEEDBACKSOURCE = _descriptor.EnumDescriptor(
  name='RobotFeedbackSource',
  full_name='proto.RobotFeedbackSource',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIMULATOR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASESTATION', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=503,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_ROBOTFEEDBACKSOURCE)

RobotFeedbackSource = enum_type_wrapper.EnumTypeWrapper(_ROBOTFEEDBACKSOURCE)
YELLOW_TEAM = 0
BLUE_TEAM = 1
SIMULATOR = 0
BASESTATION = 1



_ROBOTFEEDBACK = _descriptor.Descriptor(
  name='RobotFeedback',
  full_name='proto.RobotFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.RobotFeedback.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_sensor_sees_ball', full_name='proto.RobotFeedback.ball_sensor_sees_ball', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_sensor_is_working', full_name='proto.RobotFeedback.ball_sensor_is_working', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler_sees_ball', full_name='proto.RobotFeedback.dribbler_sees_ball', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_velocity_x', full_name='proto.RobotFeedback.estimated_velocity_x', index=4,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_velocity_y', full_name='proto.RobotFeedback.estimated_velocity_y', index=5,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_yaw', full_name='proto.RobotFeedback.estimated_yaw', index=6,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xsens_is_calibrated', full_name='proto.RobotFeedback.xsens_is_calibrated', index=7,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capacitor_is_charged', full_name='proto.RobotFeedback.capacitor_is_charged', index=8,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery_level', full_name='proto.RobotFeedback.battery_level', index=9,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=314,
)


_ROBOTSFEEDBACK = _descriptor.Descriptor(
  name='RobotsFeedback',
  full_name='proto.RobotsFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='proto.RobotsFeedback.team', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='proto.RobotsFeedback.source', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robots_feedback', full_name='proto.RobotsFeedback.robots_feedback', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=456,
)

_ROBOTSFEEDBACK.fields_by_name['team'].enum_type = _ROBOTTEAM
_ROBOTSFEEDBACK.fields_by_name['source'].enum_type = _ROBOTFEEDBACKSOURCE
_ROBOTSFEEDBACK.fields_by_name['robots_feedback'].message_type = _ROBOTFEEDBACK
DESCRIPTOR.message_types_by_name['RobotFeedback'] = _ROBOTFEEDBACK
DESCRIPTOR.message_types_by_name['RobotsFeedback'] = _ROBOTSFEEDBACK
DESCRIPTOR.enum_types_by_name['RobotTeam'] = _ROBOTTEAM
DESCRIPTOR.enum_types_by_name['RobotFeedbackSource'] = _ROBOTFEEDBACKSOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotFeedback = _reflection.GeneratedProtocolMessageType('RobotFeedback', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTFEEDBACK,
  __module__ = 'RobotFeedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotFeedback)
  ))
_sym_db.RegisterMessage(RobotFeedback)

RobotsFeedback = _reflection.GeneratedProtocolMessageType('RobotsFeedback', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTSFEEDBACK,
  __module__ = 'RobotFeedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotsFeedback)
  ))
_sym_db.RegisterMessage(RobotsFeedback)


# @@protoc_insertion_point(module_scope)
