# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotCommands.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotCommands.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13RobotCommands.proto\x12\x05proto\"\xbf\x03\n\x0cRobotCommand\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nvelocity_x\x18\x02 \x01(\x01\x12\x12\n\nvelocity_y\x18\x03 \x01(\x01\x12\x0b\n\x03yaw\x18\x04 \x01(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x05 \x01(\x01\x12\x1c\n\x14use_angular_velocity\x18\x06 \x01(\x08\x12\x1b\n\x13\x63\x61mera_yaw_of_robot\x18\x07 \x01(\x01\x12\"\n\x1a\x63\x61mera_yaw_of_robot_is_set\x18\x08 \x01(\x08\x12\x12\n\nkick_speed\x18\t \x01(\x01\x12\x15\n\rwait_for_ball\x18\n \x01(\x08\x12\x13\n\x0bkick_at_yaw\x18\x0b \x01(\x08\x12/\n\tkick_type\x18\x0c \x01(\x0e\x32\x1c.proto.RobotCommand.KickType\x12\x13\n\x0b\x64ribbler_on\x18\r \x01(\x08\x12\x12\n\nwheels_off\x18\x0e \x01(\x08\x12\x16\n\x0e\x61\x63\x63\x65leration_x\x18\x0f \x01(\x01\x12\x16\n\x0e\x61\x63\x63\x65leration_y\x18\x10 \x01(\x01\"+\n\x08KickType\x12\x0b\n\x07NO_KICK\x10\x00\x12\x08\n\x04KICK\x10\x01\x12\x08\n\x04\x43HIP\x10\x02\"<\n\rRobotCommands\x12+\n\x0erobot_commands\x18\x01 \x03(\x0b\x32\x13.proto.RobotCommandb\x06proto3')
)



_ROBOTCOMMAND_KICKTYPE = _descriptor.EnumDescriptor(
  name='KickType',
  full_name='proto.RobotCommand.KickType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_KICK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KICK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHIP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=435,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_ROBOTCOMMAND_KICKTYPE)


_ROBOTCOMMAND = _descriptor.Descriptor(
  name='RobotCommand',
  full_name='proto.RobotCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.RobotCommand.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity_x', full_name='proto.RobotCommand.velocity_x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity_y', full_name='proto.RobotCommand.velocity_y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='proto.RobotCommand.yaw', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='proto.RobotCommand.angular_velocity', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_angular_velocity', full_name='proto.RobotCommand.use_angular_velocity', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_yaw_of_robot', full_name='proto.RobotCommand.camera_yaw_of_robot', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_yaw_of_robot_is_set', full_name='proto.RobotCommand.camera_yaw_of_robot_is_set', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_speed', full_name='proto.RobotCommand.kick_speed', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wait_for_ball', full_name='proto.RobotCommand.wait_for_ball', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_at_yaw', full_name='proto.RobotCommand.kick_at_yaw', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_type', full_name='proto.RobotCommand.kick_type', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler_on', full_name='proto.RobotCommand.dribbler_on', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheels_off', full_name='proto.RobotCommand.wheels_off', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration_x', full_name='proto.RobotCommand.acceleration_x', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration_y', full_name='proto.RobotCommand.acceleration_y', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTCOMMAND_KICKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=478,
)


_ROBOTCOMMANDS = _descriptor.Descriptor(
  name='RobotCommands',
  full_name='proto.RobotCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_commands', full_name='proto.RobotCommands.robot_commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=540,
)

_ROBOTCOMMAND.fields_by_name['kick_type'].enum_type = _ROBOTCOMMAND_KICKTYPE
_ROBOTCOMMAND_KICKTYPE.containing_type = _ROBOTCOMMAND
_ROBOTCOMMANDS.fields_by_name['robot_commands'].message_type = _ROBOTCOMMAND
DESCRIPTOR.message_types_by_name['RobotCommand'] = _ROBOTCOMMAND
DESCRIPTOR.message_types_by_name['RobotCommands'] = _ROBOTCOMMANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotCommand = _reflection.GeneratedProtocolMessageType('RobotCommand', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTCOMMAND,
  __module__ = 'RobotCommands_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotCommand)
  ))
_sym_db.RegisterMessage(RobotCommand)

RobotCommands = _reflection.GeneratedProtocolMessageType('RobotCommands', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTCOMMANDS,
  __module__ = 'RobotCommands_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotCommands)
  ))
_sym_db.RegisterMessage(RobotCommands)


# @@protoc_insertion_point(module_scope)
