# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotParameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotParameters.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15RobotParameters.proto\x12\x05proto\"r\n\x0fRobotParameters\x12\x0e\n\x06radius\x18\x01 \x01(\x02\x12\x0e\n\x06height\x18\x02 \x01(\x02\x12\x13\n\x0b\x66ront_width\x18\x03 \x01(\x02\x12\x16\n\x0e\x64ribbler_width\x18\x04 \x01(\x02\x12\x12\n\nyaw_offset\x18\x05 \x01(\x02\"O\n\x0eTeamParameters\x12\x11\n\tdidChange\x18\x01 \x01(\x08\x12*\n\nparameters\x18\x02 \x01(\x0b\x32\x16.proto.RobotParametersb\x06proto3')
)




_ROBOTPARAMETERS = _descriptor.Descriptor(
  name='RobotParameters',
  full_name='proto.RobotParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius', full_name='proto.RobotParameters.radius', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='proto.RobotParameters.height', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_width', full_name='proto.RobotParameters.front_width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler_width', full_name='proto.RobotParameters.dribbler_width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw_offset', full_name='proto.RobotParameters.yaw_offset', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=146,
)


_TEAMPARAMETERS = _descriptor.Descriptor(
  name='TeamParameters',
  full_name='proto.TeamParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='didChange', full_name='proto.TeamParameters.didChange', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='proto.TeamParameters.parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=227,
)

_TEAMPARAMETERS.fields_by_name['parameters'].message_type = _ROBOTPARAMETERS
DESCRIPTOR.message_types_by_name['RobotParameters'] = _ROBOTPARAMETERS
DESCRIPTOR.message_types_by_name['TeamParameters'] = _TEAMPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotParameters = _reflection.GeneratedProtocolMessageType('RobotParameters', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTPARAMETERS,
  __module__ = 'RobotParameters_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotParameters)
  ))
_sym_db.RegisterMessage(RobotParameters)

TeamParameters = _reflection.GeneratedProtocolMessageType('TeamParameters', (_message.Message,), dict(
  DESCRIPTOR = _TEAMPARAMETERS,
  __module__ = 'RobotParameters_pb2'
  # @@protoc_insertion_point(class_scope:proto.TeamParameters)
  ))
_sym_db.RegisterMessage(TeamParameters)


# @@protoc_insertion_point(module_scope)
